// Code generated by Icestudio 0.2.3-dev
// Thu, 17 Nov 2016 21:26:32 GMT

`default_nettype none

module main (input vf649c5,
             output vad67d3);
 wire w0;
 assign vad67d3 = w0;
 assign w0 = vf649c5;
 
endmodule

